import type { Student } from "../_lib/types";

export const students: Student[] = [
  {
    id: 1,
    name: "Алекс Томпсон",
    email: "alex@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 23,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 2,
    name: "Кейси Браун",
    email: "c.brown@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "offline",
    currentQuestion: 12,
    totalQuestions: 50,
    tabSwitches: 5,
    latestAlert: {
      type: "phone",
      message: "Утас илэрсэн",
      time: "2 минутын өмнө",
    },
  },
  {
    id: 3,
    name: "Тэйлор Ли",
    email: "t.lee@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 15,
    totalQuestions: 50,
    tabSwitches: 3,
    latestAlert: {
      type: "tab",
      message: "Tab сольсон",
      time: "1 минутын өмнө",
    },
  },
  {
    id: 4,
    name: "Жордан Мартинез",
    email: "j.martinez@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 31,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 5,
    name: "Сэм Вилсон",
    email: "s.wilson@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "online",
    currentQuestion: 18,
    totalQuestions: 50,
    tabSwitches: 2,
    latestAlert: {
      type: "headpose",
      message: "Дэлгэцээс өөр тийш харсан",
      time: "3 минутын өмнө",
    },
  },
  {
    id: 6,
    name: "Жэйми Чен",
    email: "j.chen@university.edu",
    className: "МТ201 - Алгоритм",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 28,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 7,
    name: "Морган Дэвис",
    email: "m.davis@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 18,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 8,
    name: "Райли Жонсон",
    email: "r.johnson@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 42,
    totalQuestions: 50,
    tabSwitches: 1,
    latestAlert: {
      type: "tab",
      message: "Tab сольсон",
      time: "5 минутын өмнө",
    },
  },
  {
    id: 9,
    name: "Крис Эванс",
    email: "c.evans@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 27,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 10,
    name: "Эмма Гарсиа",
    email: "e.garcia@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "offline",
    currentQuestion: 9,
    totalQuestions: 50,
    tabSwitches: 4,
    latestAlert: {
      type: "people",
      message: "Нэмэлт хүн илэрсэн",
      time: "4 минутын өмнө",
    },
  },
  {
    id: 11,
    name: "Ноа Уокер",
    email: "n.walker@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 34,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 12,
    name: "Оливиа Холл",
    email: "o.hall@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 11,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 13,
    name: "Лиам Аллен",
    email: "l.allen@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "online",
    currentQuestion: 21,
    totalQuestions: 50,
    tabSwitches: 2,
    latestAlert: {
      type: "phone",
      message: "Утас илэрсэн",
      time: "6 минутын өмнө",
    },
  },
  {
    id: 14,
    name: "София Янг",
    email: "s.yang@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 39,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 15,
    name: "Итан Кинг",
    email: "e.king@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "offline",
    currentQuestion: 16,
    totalQuestions: 50,
    tabSwitches: 3,
    latestAlert: {
      type: "headpose",
      message: "Дэлгэцээс өөр тийш удаан харсан",
      time: "7 минутын өмнө",
    },
  },
  {
    id: 16,
    name: "Миа Скотт",
    email: "m.scott@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "online",
    currentQuestion: 25,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 17,
    name: "Лукас Грин",
    email: "l.green@university.edu",
    className: "МТ201 - Алгоритм",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 34,
    tabSwitches: 1,
    latestAlert: {
      type: "tab",
      message: "Илгээхийн өмнө Tab сольсон",
      time: "35 минутын өмнө",
    },
  },
  {
    id: 18,
    name: "Шарлотт Адамс",
    email: "c.adams@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 29,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 19,
    name: "Бенжамин Нельсон",
    email: "b.nelson@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "online",
    currentQuestion: 14,
    totalQuestions: 50,
    tabSwitches: 1,
    latestAlert: {
      type: "people",
      message: "Камерт өөр хүн орж ирсэн",
      time: "8 минутын өмнө",
    },
  },
  {
    id: 20,
    name: "Амелия Картер",
    email: "a.carter@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 45,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 21,
    name: "Хенри Митчелл",
    email: "h.mitchell@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "submitted",
    currentQuestion: 50,
    totalQuestions: 50,
    submittedMinutesAgo: 9,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 22,
    name: "Харпер Робертс",
    email: "h.roberts@university.edu",
    className: "МТ102 - Өгөгдлийн бүтэц",
    status: "offline",
    currentQuestion: 7,
    totalQuestions: 50,
    tabSwitches: 6,
    latestAlert: {
      type: "tab",
      message: "Олон удаа Tab сольсон",
      time: "1 минутын өмнө",
    },
  },
  {
    id: 23,
    name: "Дэниел Тернер",
    email: "d.turner@university.edu",
    className: "МТ201 - Алгоритм",
    status: "online",
    currentQuestion: 20,
    totalQuestions: 50,
    tabSwitches: 0,
    latestAlert: null,
  },
  {
    id: 24,
    name: "Эвелин Филлипс",
    email: "e.phillips@university.edu",
    className: "МТ101 - Компьютерын ухааны үндэс",
    status: "online",
    currentQuestion: 11,
    totalQuestions: 50,
    tabSwitches: 2,
    latestAlert: {
      type: "phone",
      message: "Гарт төхөөрөмж илэрсэн",
      time: "9 минутын өмнө",
    },
  },
];
